import Head from "next/head";
import Image from "next/image";
import Script from "next/script";

import Header from "@components/Header";
import Container from "@components/Container";
import Button from "@components/Button";
import products from "@data/products.json";

import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link
          rel="stylesheet"
          href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css"
        />
      </Head>
      <Header />
      <main>
        <Container>
          <h1>Developer833&apos;s Headless Wordpress Ecommerce Test</h1>
          <h2>Available Cards</h2>
          <ul className={styles.products}>
            {products.map((product) => {
              return (
                <li key={product.id}>
                  <Image
                    src={product.image}
                    alt={`Card of ${product.title}`}
                    width={864}
                    height={1200}
                  />
                  <h3>{products.title}</h3>
                  <p>{product.price}</p>
                  <p>
                    <Button
                      className="snipcart-add-item"
                      data-item-id={product.id}
                      data-item-price={product.price}
                      data-item-url="/"
                      data-item-description=""
                      data-item-image={product.image}
                      data-item-name={product.title}
                    >
                      Add to Cart
                    </Button>
                  </p>
                </li>
              );
            })}
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        &copy; eight33digital.com, {new Date().getFullYear()}
      </footer>
      <link
        rel="stylesheet"
        href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css"
      />
      <Script
        async
        src="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.js"
      />
      <div
        id="snipcart"
        data-config-modal-style="side"
        data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}
        hidden
      ></div>
    </div>
  );
}
